from langchain_core.prompts import PromptTemplate

question_template = PromptTemplate(
    input_variables=["packet_name","packet_name_2","packet_name_fields","packet_name_2_fields"],
    template = """
    As a Bluetooth protocol expert, you need to analyze the direct dependencies between the two data packet parameters of {packet_name} and {packet_name_2}.
    Please follow these steps for professional analysis:
    <data packet definition> 
    <{packet_name} fields> {{
      {packet_name_fields}
    }} </{packet_name} fields > 
    <{packet_name_2} fields> {{
      {packet_name_2_fields}
    }} </{packet_name_2} fields >
    </data packet definition > 
    Analysis requirements: 
    1. Strictly analyze based on the provided {packet_name} fields and {packet_name_2} fields without omitting or fabricating any fields.
    2. Direct dependency is defined as: The parameter value in one data packet directly affects or determines the setting of the parameter value in another data packet. 
    3. Consider the constraints between the parameters defined by the protocol specification 
    4. Exclude indirect effects or associations generated by intermediate parameters.
    Complete it in the < think > tag: 
    1. List the protocol definition of each parameter 
    2. Analyze the direct causal relationship between the parameters 
    3. Record the excluded indirect associations. 
    Output requirements: 
    1. Use strict JSON format 
    2. Contain boolean cross_packet_dependency fields 
    3. Describe each parameter pair relationship with key-value pairs in the explanation field 
    4. Keeping the same field structure as the example. 
    the example output structure: 
    {{
      "packet_name": "{packet_name}", 
      "packet_name_2": "{packet_name_2}", 
      "cross_packet_dependency": [true/false], 
      "explanation": {{
        "Parameter Pair 1": "Analysis Instructions", 
        "Parameter Pair 2": "Analysis Instructions", 
        "...": "Analysis Instructions"
      }}
    }}
     Only output the final JSON result.
    """
)


# question_template = PromptTemplate(
#     input_variables=["packet_name","packet_name_2","packet_name_fields","packet_name_2_fields"],
#     template = """
#     As a Bluetooth protocol expert, you need to analyze the direct dependencies between the two data packet parameters of {packet_name} and {packet_name_2}.
#     Please follow these steps for professional analysis:
#     <data packet definition> 
#     <{packet_name} fields> {{
#       {packet_name_fields}
#     }} </{packet_name} fields > 
#     <{packet_name_2} fields> {{
#       {packet_name_2_fields}
#     }} </{packet_name_2} fields >
#     </data packet definition > 
#     Analysis requirements: 
#     1. Strictly analyze based on the provided {packet_name} fields and {packet_name_2} fields without omitting or fabricating any fields.
#     2. Direct dependency is defined as: The parameter value in one data packet directly affects or determines the setting of the parameter value in another data packet. The calculation of parameters in one data packet depends on the parameters from another data packet. 
#     3. Consider the constraints between the parameters defined by the protocol specification 
#     4. Exclude indirect effects or associations generated by intermediate parameters.
#     Complete it in the < think > tag: 
#     1. List the protocol definition of each parameter 
#     2. Analyze the direct causal relationship between the parameters 
#     3. Record the excluded indirect associations. 
#     Output requirements: 
#     1. Use strict JSON format 
#     2. Contain boolean cross_packet_dependency fields 
#     3. Describe each parameter pair relationship with key-value pairs in the explanation field 
#     4. Keeping the same field structure as the example. 
#     the example output structure: 
#     {{
#       "packet_name": "{packet_name}", 
#       "packet_name_2": "{packet_name_2}", 
#       "cross_packet_dependency": [true/false], 
#       "explanation": {{
#         "Parameter Pair 1": "Analysis Instructions", 
#         "Parameter Pair 2": "Analysis Instructions", 
#         "...": "Analysis Instructions"
#       }}
#     }}
#      Only output the final JSON result.
#     """
# )

def get_question(packet_name,packet_name_2,packet_name_fields,packet_name_2_fields):
    return question_template.format(packet_name=packet_name,packet_name_2=packet_name_2,packet_name_fields=packet_name_fields,packet_name_2_fields=packet_name_2_fields)




if __name__ == "__main__":
    print(get_question(packet_name="ll connection update ind",packet_name_2="ll terminate ind",packet_name_fields="RFU,MD,SN,NESN,LLID,len",packet_name_2_fields="Reason,LLID,len"))