

from langchain_core.prompts import PromptTemplate


#  """"You are a Bluetooth protocol expert tasked with analyzing the protocol specifications within a technical document.
# The specific task is to analyze a particular packet field defined in the document and determine the most likely seed for fuzz testing mutations of this field.Please carefully review the protocol document:
# Here are the specific steps for the analysis:
# Locate the packet named {packet_name} within the document.
# Conduct a detailed analysis of the {field} field within this packet.
# Initially explore the boundary values of this field as the starting seeds for fuzz testing mutations.
# Taking into account the semantics of the field and any possible constraints mentioned in the document, determine the most probable seed for fuzz testing mutations.
# In the <thinking> tag, provide a detailed analysis of your reasoning for determining the fuzz testing mutation seed. Then, in the <answer> tag, provide the final answer, following the example format, which includes the semantic description, defined values, and fuzz testing seed.
# <thinking>
# [Here, detail your analytical process for determining the fuzz testing mutation seed]
# </thinking>
# <answer>
# [semantic:'[Fill in the semantic description of the field]',defined_values:'[Fill in the defined values]',fuzz_seed:'[Fill in the fuzz testing seed]']
# </answer>
# """

template ="""
As a Bluetooth protocol expert, please perform the following protocol analysis task:

Analysis Objective: Determine the optimal fuzz testing mutation seed for the {field} field
Analysis Target: The {field} field in the {packet_name} packet

Execution Steps:

Locate Packet Structure

Accurately identify the definition of the {packet_name} packet in the protocol document.

Field Semantic Analysis

Parse the binary structure of the {field} field.

Extract the intended purpose and functional description of the field.


Value Range Derivation
a. Basic Value Range:

Determine the bit-length of the field.

Calculate the theoretical minimum (0) and maximum (2^n - 1) values.

b. Semantic Value Range:

Extract descriptions of reserved bits.

Analyze dependencies between fields.

c. Seed Selection Strategy

Generate the maximum and minimum values that conform to the field's data type.

Generate values smaller than the semantically defined minimum and larger than the maximum value.

Mutate the values based on bit-flipping strategies.

Generate random values.

Filter out any values that do not fall within the defined data type range.

Output Requirements:
Present the analysis results in the <answer> tag using the following structure:
[semantic:'Field functional description', defined_values:'All defined valid value enumeration', fuzz_seed:'The seeds generated by the Seed Selection Strategy retain the fuzzing seed exclusively in hexadecimal format.']

Example:
<answer>
    <semantic>Defines the input and output capabilities of a Bluetooth device, influencing the selection of pairing methods and security levels.</semantic>
    <defined_values>0x00 (DisplayOnly), 0x01 (DisplayYesNo), 0x02 (KeyboardOnly), 0x03 (NoInputNoOutput), 0x04 (KeyboardDisplay), 0x05-0xFF (Reserved for future use)</defined_values>
    <fuzz_seed>0x00, 0x04, 0x03, 0x01, 0xFF, 0x02, 0x05, 0x0A, 0x07, 0x08, 0x10, 0x60</fuzz_seed>
</answer>

Do not include any additional text or explanations outside of this XML format.
"""
SemExtPrompt = PromptTemplate(
    input_variables=["packet_name", "field"],  # 定义模板中的变量
    template=template,  # 模板内容
)

# prompt = SemExtPrompt.format(packet_name="pairing request", field="io_cap")
# print(prompt)
def get_prompt(packet_name, field):
    return SemExtPrompt.format(packet_name=packet_name, field=field)

# # 预定义示例
# examples = [
#     {
#         "input": "2+2",
#         "output": "4"
#     },
#     {
#         "input": "3*5",
#         "output": "15"
#     },
#     {
#         "input": "10-4",
#         "output": "6"
#     }
#     ]

# # 创建示例模板
# example_prompt = PromptTemplate(
#     input_variables=["question", "answer"],
#     template="question: {question}\nanswer: {answer}\n"
# )

# # 组合 FewShot Prompt
# cot_few_shot = FewShotPromptTemplate(
#     examples=examples,
#     example_prompt=example_prompt,
#     prefix="As a Bluetooth protocol expert, you need to analyze the protocol specifications in technical documents. Please follow these professional analysis steps:1.Identify all packet types defined in the protocol layers within the document.2.Perform a field-by-field analysis for each packet, including:field Name ,Semantic Description, Defined Values (Specific numerical values)\n",
#     suffix="query: {query}\n\nhint:{hint} ",
#     input_variables=["query","hint"]
# )

# # 生成 Prompt
# # formatted_prompt = cot_few_shot.format(query="如果 8 个工人 4 天造 32 把椅子，16 个工人 8 天能造多少把椅子？",hint="先计算一个工人一天造多少把椅子")
# def get_prompt():
#     formatted_prompt = cot_few_shot.format(query="packet name:pairing request,field:auth_req",hint="Please analyze the specification and determine the most likely seeds for fuzzing mutations of this field. Start by exploring the boundary values of the field for the initial few cases. Answer according to the example format.")
#     return formatted_prompt
if __name__ == "__main__":
    print(get_prompt())
