from langchain.prompts import PromptTemplate

SemRspPrompt = PromptTemplate(
            input_variables=["INSEQ","OUTSEQ"],
            template="""
    As a Bluetooth Core protocol expert, you need to verify that the packet sequence responses generated by the fuzz test conform to the protocol specification. 
    < InputPackets > {INSEQ} </InputPackets >
    < OutputPackets > {OUTSEQ} </OutputPackets >
    Please follow these steps for rigorous analysis: 
    < Protocol Framework > Verification should be based on: 1. Security Manager Protocol (SMP) fine-state machine 2. Link Layer (LL) Control Procedures </Protocol Framework > 
    < Verification Steps > 
    1. Generate the correct output packet sequence from the input packet sequence: < InputPackets > {INSEQ} </InputPackets>
    
    2. Verify by phase: 
    please verify each packet in the input packet sequence and the output packet sequence one by one.
    Phase 1 - Final-state machine integrity:
        • Check that the response of each LL control packet meets the synchronization status requirements 

    Phase 2 - SMP process verification:
        • Verify the pairing phase (Pairing Phase) Transformation sequence: 
        - Phase1: Capability Exchange 
        - Phase2: Authentication & Key Generation 
        - Phase3: Key Distribution 
    Phase 3 - Encryption Information Exchange:
        • Phase 2 must be completed before Phase 3
        • Verify the chronological order of master identification and encryption startup
        • ll_pause_enc_req_pkt must be sent after Encryption Information Exchange

    </verification steps > 
    < determination criteria > Give conclusions in < Judgment >: • "Correct": Fully comply with the protocol fine-state machine and response rules • "Incorrect": There is a sequence of operations that violate the specification • "Inconclusive": Unverifiable responses or missing key protocol contexts, in < Explanation > must contain: 1. Specification clause number violated (e.g. Core Spec v5.2 Vol3 Chapter H, Section 2.3.4) 2. Specific conversion nodes for finite-state machine errors 3. Timing conflicts in secure processes (e.g. key exchange order errors) 4. Unhandled exception conditions (if any) </decision criteria > 
    < output format > 
    Generate a JSON response that strictly conforms to the following structure: {{"Input": "{{INPUT_PACKET_SEQUENCE}}", "Output": "{{OUTPUT_PACKET_SEQUENCE}}", "Judgment": "[correct/incorrect/inconclusive]", "Explanation": "Point-by-point description of technical basis..." Note: Specific agreement terms must be referenced, for example: "According to Core Spec v5.2 Vol3 H Chapter 3.5.1, sending encryption_information_pkt when Phase2 is not completed violates the key distribution order" }}
    </output format >
    """
        )

def get_prompt(INSEQ, OUTSEQ):
    return SemRspPrompt.format(INSEQ=INSEQ, OUTSEQ=OUTSEQ)

if __name__ == "__main__":
    print(get_prompt(INSEQ="(ll_feature_req_pkt),(ll_length_req_pkt),(ll_version_ind_pkt),(pairing_request_pkt),(pairing_public_key_pkt),(master_identification_pkt),(encryption_information_pkt),(encryption_information_pkt),(ll_enc_req_pkt),(ll_start_enc_rsp_pkt),(ll_pause_enc_req_pkt)", OUTSEQ="(ll_feature_rsp_pkt),(ll_length_rsp_pkt),(ll_version_ind_pkt),(pairing_response_pkt),(pairing_confirm_pkt,pairing_public_key_pkt),(pairing_failed_pkt),(empty),(empty),(ll_enc_rsp_pkt,ll_reject_ind_ext_pkt),(ll_connection_param_req_pkt),(empty)"))




